### ISSUE TITLE
selecting a time using input-time resets the Date to epoch

### ISSUE THREAD

**Issue by joebartels** [lozjackson/ember-time-tools#32]
When using `{{input-time value=someDate}}` and selecting a time, it has the effect of resetting `someDate` back to epoch.

It seems to be intentional:
https://github.com/lozjackson/ember-time-tools/blob/master/addon/components/tt-time-picker.js#L178

but I personally would prefer its behavior to not alter the date. Thoughts?

**Comment by lozjackson** [comment]
I will look into adding this as an option

**Comment by lozjackson** [comment]
If you comment out that line do you get the behaviour you want?

**Comment by lozjackson** [comment]
I've added a PR that provides a `resetDate` option (defaults to true).. would appreciate it if you would take a look and let me know if I'm on the right track with regards to your request.

It basically removes the `0` from the `new Date()` call. so you get a date that defaults to now.. and then the hours and minutes of that date object are set to the selected time.

**Comment by joebartels** [comment]
The use case for me is a calendar of events from various dates and I'm using `{{input-time}}` to let the user change only the time of the event.

What I've done as a "workaround" is split the date and the time into separate computed properties and then reconstitute them with a 3rd computed property.
```js
{
  startDate: computed.reads('eventDateTime'),

  startTime: computed.reads('eventDateTime'),

  startDateTime: computed('startDate', 'startTime', function() {
    const { startDate, startTime } = this.getProperties('startDate', 'startTime');
    const startDateTime = copyDate(startDate);

    startDateTime.setHours(startTime.getHours(), startTime.getMinutes());

    return startDateTime;
  }).readOnly()
}
```
And then I just do `{{input-time value=startTime}}` and `{{input-date value=startDate}}`

When it comes time to save the event, I just grab `startDateTime`.

Defaulting to today's date doesn't suit my use case but perhaps it will suit others'

**Comment by lozjackson** [comment]
I have a very similar use case where I'm using an `input-time` and `input-date` component to enable setting either date or time part of an event.. and basically do the same thing with a third computed property to sum the two.

Thats always worked well enough for me, and I've had no reason to improve on that.. but I am interested in looking into a better solution.. that doesn't need a third property.

If you have any ideas for a better solution, please share.. and feel free to contribute..

**Comment by joebartels** [comment]
I hear you. I'd love to look a little deeper into the addon. Will update this thread if I come up with anything worthwhile! 
Thanks!

**Comment by lozjackson** [comment]
Its ok, I have a working solution.. just playing around with it now.. but something along the lines of

```js
let date = new Date(this.get('selectedTime') || 0);
```

is working well for me (on that line you linked to)

**Comment by lozjackson** [comment]
Take a look at PR #34 Does that fit your requirement a bit better

**Comment by lozjackson** [comment]
This is working well for me, so I'm going to merge it..

You can then try it, and if it doesn't work well for you feel free to re-open the issue (or start a new one).  ...Or if you have any other ideas for improvement I'd love to hear them.

**Comment by lozjackson** [comment]
I published this change in `v0.8.0`

**Comment by joebartels** [comment]
Change looks and works great for me also. Thank you!

**Comment by lozjackson** [comment]
No problem
