### ISSUE TITLE
Installing this addon breaks acceptance testing

### ISSUE THREAD

**Issue by scroggic** [lozjackson/ember-time-tools#38]
This appears to be a repeatable issue - I've verified on basic test application and my current project. After installing this addon, acceptance tests time out, with the following messages: 

_"Tried to restart test while already started (test's semaphore was 0 already)"_ and _"TypeError: currentURL is not a function."_

Removing just this addon immediately corrects things.

I'm investigating what could be the cause, but I just thought I'd let you know.

**Comment by lozjackson** [comment]
@scroggic Thanks for letting me know.

If you have a failing test i'd appreciate a PR...  (even better if you have a fix too)

**Comment by lozjackson** [comment]
This addon uses [ember-clock](https://github.com/lozjackson/ember-clock).

And this issue has been reported there.  [See here](https://github.com/lozjackson/ember-clock/issues/1).  It was not really resolved properly.. but the workaround is to disable the clock service during tests.  not ideal.. If you can think of a better way then I'm interested in seeing it.

**Comment by scroggic** [comment]
@lozjackson - thanks for the quick reply. I've gone ahead and used that workaround in order to keep rolling on what I'm working on, but I will let you know if I/we come up with a different approach.
