### ISSUE TITLE
Use custom CSS classes

### ISSUE THREAD

**Issue by belgoros** [lozjackson/ember-time-tools#41]
If I'm not mistaken, there is no way to pass in CSS `class` option to `{{input-time}}` tag, right ? Whatever I tried, it does take it into account, the only way I see is to use in-line style tag.

**Comment by lozjackson** [comment]
Have you tried adding the class directly in the template.. something like

```hbs
{{input-time class="custom-css-classname"}}
```

That should add the css class to the `input-time` component.  However, that component is simply a wrapper for the `time-picker` and 'time-field` components, which may be where you really want the classes added... if so you may be able to target those components by using something like this in your style sheet

```css
.input-time .tt-time-picker {
  ...
}
```

Hope that helps, let me know if you have any other Qs.. and if there is anything that can be done to make this easier then I'm all ears.. (again PRs welcome)

**Comment by belgoros** [comment]
OK, thank you, I'll take a try (either one or another solution you posted). I'll close the issue.

**Comment by belgoros** [comment]
Using a custom CSS as you suggested didn't solve the problem:
<img width="449" alt="screen shot 2018-04-13 at 16 13 40" src="https://user-images.githubusercontent.com/83579/38739639-c622ee56-3f35-11e8-8e1e-357ae05bd534.png">

It looks as if the `input-time` input textfield is inside another one. Here the code I used:
```
<div class="form-row">
        <div class="form-group col-sm-4">
          {{input-time
            placeholder="Select a time"
            value=time
            displayFormat='HH:mm'
            pickerDisplayFormat='hh:mm'
            scrollToSelectedTime=false
            class="form-control"
          }}
        </div>
      </div>
```

**Comment by lozjackson** [comment]
The input element is wrapped inside a d containing div element.  The structure looks something like this:
```
<div class="input-time">

  <input class="tt-time-field">
  
  <div class="...">
    <div class="tt-time-picker">
       ...
    </div>
  </div>
</div>
```
`input-time` is a (`div`) container, `tt-time-field` is the `input` element. `tt-time-picker` is the time picker component

So, to target the input text field you could do something like `.input-time tt-time-field`.

What are you trying to do?

You could import/extend the `input-time` component in your app, copy the template and modify it so that it passes a class name to the input element.

**Comment by belgoros** [comment]
Thank you for your response. I think the lost flexible solution (at least for the future use) would be to enable to pass in a CSS class like[ ember-power-select ](https://github.com/cibernox/ember-power-select)does, for example. Otherwise, the look of the above input is really not very nice and would be limited.

**Comment by lozjackson** [comment]
You could extend the `time-field` component to add your class like this:

```js
import TimeFieldComponent from 'ember-time-tools/components/tt-time-field';

export default TimeFieldComponent.extend({

  classNames: ['form-control']
});
```
Then any time you use `{{input-time}}` in your app it will have the `form-control` class added.  Thats is the easiest way to customise the class applied to the input element.. and can be done today without updating the addon.

If that doesn't work for you then let me know what the API you think would work and I'll see if I can . implement something.
